name: GRIP deploy

on:
  push:
  
env:
  spn_client_id: 0e742c50-7833-42da-8580-d9509eb14bd2
  tenant_id: 93f33571-550f-43cf-b09f-cd331338d086
  subscription_id: 6bc2e318-d6fd-4cde-a71c-007eb05321c5
  rg_name: griprg
  plan_name: gripplan
  location: westeurope
  web_app_name: Grip-webapp
  #AZURE_WEBAPP_NAME: DAMS
  #AZURE_WEBAPP_PACKAGE_PATH: 'DigitalAsset'
  #DOTNET_VERSION: '6.0.401'

permissions:
  id-token: write
  contents: read

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:

    - uses: azure/login@v1
      with:
        client-id: ${{ env.spn_client_id }}
        tenant-id: ${{ env.tenant_id }}
        subscription-id: ${{ env.subscription_id }}

    - run: az group create -l ${{ env.location }} -n ${{ env.rg_name }}
      name: Deploy rg

    - run: az appservice plan create -g ${{ env.rg_name }} -n ${{ env.plan_name }} --sku F1
      name: Deploy plan

    - uses: actions/checkout@v3

    #- run: az webapp up --sku F1 -p ${{ env.plan_name }} -n ${{ env.web_app_name }} --os-type windows -g ${{ env.rg_name }} -l ${{ env.location }}
    #  name: Deploy default app
    #  working-directory: DigitalAsset


    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      working-directory: DigitalAsset
      
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ../da-app -r linux-x64 --self-contained true /p:UseAppHost=true
        Compress-Archive da-app/* grip.zip
      working-directory: DigitalAsset

    - run: az webapp deployment source config-zip --src grip.zip
      name: actual deploy
      working-directory: DigitalAsset

    #- run: az webapp deploy -g ${{ env.rg_name }} -n ${{ env.web_app_name }} --src-path SourcePath --type zip
    #  name: deploy as zip
    #  working-directory: DigitalAsset/da-app

    #- name: Test
    #  run: |
    #    cd DotNet.WebApp.Tests
    #    dotnet test --no-restore --verbosity normal
      
    #- uses: azure/webapps-deploy@v2
    #  name: Deploy
    #  with:
    #    app-name: ${{ env.AZURE_WEBAPP_NAME }}
    #    publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
    #    package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/dotnet-webapp'